# Generated by Django 4.1.7 on 2023-05-06 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='imageUrl',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
